stages:

  annotation:
    cmd: python src/create_annotation.py params.yaml
    deps:
    - src/create_annotation.py
    - ${annotation.folder_images}
    params:
    - annotation
    outs:
    - ${annotation.filename_annotation}

  design:
    cmd: python src/create_design.py params.yaml
    deps:
    - src/create_design.py
    - ${design.filename_annotation}
    params:
    - design
    outs:
    - ${design.filename_save}

  cv_resnet:
    cmd: python src/cv_resnet.py params.yaml
    deps:
    - src/cv_resnet.py
    - ${cv_resnet.filename_design}
    - ${cv_resnet.folder_images}
    params:
    - cv_resnet

  optunize_resnet:
    cmd: python src/optunize_resnet.py params.yaml
    deps:
    - src/optunize_resnet.py
    - src/cv_resnet.py
    params:
    - cv_resnet
    - optunize_resnet
