shared:
  seed: 202208
  mlflow_tracking_uri: http://localhost:5009


annotation:
  folder_images: data/raw/images
  filename_annotation: data/raw/annotation.csv


design:
  filename_annotation: data/raw/annotation.csv
  filename_save: "data/design.csv"
  kfold_splits: 4
  val_size: 0.05


cv_resnet:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/cv_resnet/best
  folder_output_report: reports/cv_resnet/best

  column_fold: fold_author
  folds_use: [0, 1, 2, 3]

  model_name: resnet18
  retrain_type: fc  # options: full, fc, none

  n_epochs: 50
  batch_size: 32
  optimizer:
    name: Adam
    lr: 0.001 
    
  label_smoothing: 0.0

  save_model_checkpoints: false


optunize_resnet:
  base_model_list:
  - resnet18
  - resnet34
  - resnet50
  retrain_type_list:
  - fc
  - full
  lr:
    min: 0.001
    max: 0.05
