shared:
  seed: 202208
  mlflow_tracking_uri: http://localhost:5009


annotation:
  folder_images: data/raw/images
  filename_annotation: data/raw/annotation.csv


design:
  filename_annotation: data/raw/annotation.csv
  filename_save: "data/design.csv"
  kfold_splits: 4
  val_size: 0.05


cv_resnet18:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/cv_resnet18
  folder_output_report: reports/cv_resnet18

  column_fold: fold_author
  folds_use: [0]

  n_epochs: 100
  batch_size: 64
  optimizer:
    name: Adam
    lr: 0.001 
    
  label_smoothing: 0.0

  save_model_checkpoints: false
