shared:
  seed: 202208
  mlflow_tracking_uri: http://localhost:5009


annotation:
  folder_images: data/raw/images
  filename_annotation: data/raw/annotation.csv


design:
  filename_annotation: data/raw/annotation.csv
  filename_save: "data/design.csv"
  kfold_splits: 4
  val_size: 0.05


optunize_random_forest:

  filename_input: "./data/predictions/combo.csv"

  n_trials: 100

  column_fold: fold_author

  folds_use:
  - 3

  hyperparams:
    n_estimators:
      min: 10
      max: 1000
    max_depth: 
      min: 2
      max: 32
    min_samples_leaf:
      min: 1
      max: 32
    min_samples_split:
      min: 2
      max: 32

  use_pca:
    - true
    - false

  mlflow_experiment: optunize_random_forest


train_nn_classifier:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/train_nn_classifier/best
  folder_output_report: reports/train_nn_classifier/best

  column_fold: fold_author
  folds_use: [0, 1, 2, 3]

  # labels_use:
  #   # - japonism
  #   - photo
  #   - cubism

  params_embedder:
    resnet_name: resnet18
    embedding_size: 16
    freeze_resnet_cnn: false
    freeze_resnet_fc: false

  n_epochs: 50
  batch_size: 32

  top_k_list:
  - 1
  - 2
  - 3
  score_target: top_2_accuracy
  label_smoothing: 0.0

  optimizer:
    lr: 0.0001
    weight_decay: 0.
  scheduler:
    # gamma = np.power(lr_final / lr, 1 / n_epochs)
    lr_final: 0.00001
    
  save_model_checkpoints: true
  mlflow_experiment: train_nn_classifier
  device: mps


optunize_nn_classifier:
  n_trials: 100

  resnet_name_list:
  - resnet18
  # - resnet34
  - resnet50

  freeze_resnet_fc_list:
  - true
  # - false

  freeze_resnet_cnn_list:
  - true
  - false

  lr:
    min: 0.0001
    max: 0.01

  embedding_size:
    min: 2
    max: 64
    
  mlflow_experiment: train_nn_classifier


predict_nn_classifier:
  mlflow:
    experiment_name: train_nn_classifier
    run_id: ca8ff65afb5744a2bde060f116d70a22
  device:
    "mps"  
  folder_output:
    data/predictions


train_embedder:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/train_embedder/best
  folder_output_report: reports/train_embedder/best

  score_target: silhouette_score

  labels_test:
    - photo
    - naturalism

  params_embedder:
    resnet_name: resnet18
    embedding_size: 3
    freeze_resnet_cnn: false
    freeze_resnet_fc: false

  n_epochs: 100
  batch_size: 32

  optimizer:
    lr: 0.0001
    weight_decay: 0

  optimizer_loss:
    lr: 0.001

  scheduler:
    lr_final: 0.00001
    
  save_model_checkpoints: false
  mlflow_experiment: train_embedder
  device: mps
