shared:
  seed: 202208
  mlflow_tracking_uri: http://localhost:5009


annotation:
  folder_images: data/raw/images
  filename_annotation: data/raw/annotation.csv


design:
  filename_annotation: data/raw/annotation.csv
  filename_save: "data/design.csv"
  kfold_splits: 4
  val_size: 0.05


cv_resnet:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/cv_resnet/best
  folder_output_report: reports/cv_resnet/best

  column_fold: fold_author
  folds_use: [3]

  model_name: resnet18
  retrain_type: full  # options: full, fc, none

  n_epochs: 50
  batch_size: 32
  optimizer:
    name: Adam
    lr: 0.00001 
    
  label_smoothing: 0.0

  save_model_checkpoints: true


optunize_resnet:
  n_trials: 10
  base_model_list:
  - resnet18
  # - resnet34
  # - resnet50
  retrain_type_list:
  # - fc
  - full
  lr:
    min: 0.00001
    max: 0.001


metric_learning_resnet:
  filename_design: data/design.csv
  folder_images: data/raw/images

  folder_output_model: models/metric_learning_resnet/best
  folder_output_report: reports/metric_learning_resnet/best

  column_fold: fold_author
  folds_use: [3]

  model_name: resnet18
  retrain_type: full  # options: full, fc, none
  embedding_size: 8  # well... 2^3 = 8

  n_epochs: 50
  batch_size: 128
  optimizer:
    name: Adam
    lr: 0.0001
  scheduler:
    gamma: 0.9
    
  save_model_checkpoints: true
  mlflow_experiment: metric_learning_resnet


embedding_size_search:
  model_name: resnet18
  retrain_type: full
  embedding_size_list:
  - 8
  - 16
  - 64
  mlflow_experiment: metric_learning_resnet
